### ISSUE TITLE
Hardcode laminas-log to version 2.15.2

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-log#17]
because laminas-log  2.15.3 messed something 

https://github.com/laminas/laminas-log/pull/43

and make a new release #https://github.com/laminas/laminas-log/pull/43

**Comment by bidi47** [comment]
laminas-log 2.15.3 currently causes this error
Uncaught Laminas\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "dot-log.default_logger" to a factory; are you certain you provided it during configuration?

updated composer with laminas-log fixed version 2.15.2 until a fix is implemented in dot packages
https://github.com/dotkernel/dot-log/pull/18
