### ISSUE TITLE
why is asking an old version of laminas-log ?

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-log#23]
Problem 1
    - Root composer.json requires laminas/laminas-log 2.15.2 -> satisfiable by laminas/laminas-log[2.15.2].
    - laminas/laminas-log 2.15.2 requires php ^7.4 || ~8.0.0 || ~8.1.0 -> your php version (8.2.8) does not satisfy that requirement.

**Comment by arhimede** [comment]
"laminas/laminas-log": "2.15.2",

check if there was a reason why is hardcoded to one version

**Comment by bidi47** [comment]
related to https://github.com/dotkernel/dot-log/issues/17
